name: re_os
profile: re_os
config-version: 2
version: 1.0.0

model-paths:
  - models/marts
test-paths:
  - tests
analysis-paths:
  - analyses
docs-paths:
  - docs
target-path: target
clean-targets:
  - target
  - logs

vars:
  psf_min: 2000
  psf_max: 25000
  months_supply_undersupply: 9
  months_supply_oversupply: 18

on_run_end:
  - "{{ log('dbt run completed for re_os', info=True) }}"

models:
  re_os:
    marts:
      +materialized: view
      +tags: "marts"
