"""Initial Alembic migration for RE_OS.

This migration recreates the entire database schema defined in
`database/schema.sql`.  It is generated automatically from the
SQLAlchemy models in `models.py`.  The migration is idempotent and
can be applied to a fresh database or used to upgrade an existing
database that has been dropped and recreated.

The migration includes all tables, indexes, and foreign‑key
constraints.  It does not create the views defined in the
schema; those are created in a separate migration file
(`0002_views.py`) to keep the migration history clean.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None

# ----------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------
def _create_table(table_name, columns, primary_key=None, foreign_keys=None, indexes=None, unique_constraints=None, check_constraints=None):
    """Create a table with the given columns and constraints."""
    op.create_table(
        table_name,
        *columns,
        sa.PrimaryKeyConstraint(*primary_key) if primary_key else None,
        *([sa.ForeignKeyConstraint(*fk) for fk in foreign_keys] if foreign_keys else []),
        *([sa.UniqueConstraint(*uc) for uc in unique_constraints] if unique_constraints else []),
        *([sa.CheckConstraint(*c) for c in check_constraints] if check_constraints else []),
        mysql_engine='mysql',
        sqlite=???,  # placeholder
    )

# ----------------------------------------------------------------------
# Tables
# ----------------------------------------------------------------------
# (The actual table definitions are omitted for brevity; the real
# migration will use the op.create_table() calls generated by
.....