"""simplify_models_phase1_baseline

Revision ID: 78bc2a7eefb9
Revises: 0003_board_sessions
Create Date: 2026-05-21 11:08:53.818148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: Union[str, None] = '0003_board_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_memories', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.6'))
    op.alter_column('agent_memories', 'source_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_memories', 'last_confirmed',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('agent_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_memories_agent'), table_name='agent_memories')
    op.drop_index(op.f('idx_agent_memories_confidence'), table_name='agent_memories')
    op.alter_column('agent_runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'started'::character varying"))
    op.alter_column('agent_runs', 'records_scraped',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_inserted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_updated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_runs_status'), table_name='agent_runs')
    op.alter_column('developers', 'total_projects',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'completed_projects',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'delayed_projects',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'total_units_launched',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'total_units_sold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('developers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('developers_name_normalized_key'), table_name='developers', postgresql_where='(name_normalized IS NOT NULL)')
    op.drop_index(op.f('idx_developers_name_trgm'), table_name='developers', postgresql_using='gin')
    op.alter_column('guidance_values', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kaveri_registrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_kaveri_date'), table_name='kaveri_registrations')
    op.drop_index(op.f('idx_kaveri_geom'), table_name='kaveri_registrations', postgresql_using='gist')
    op.drop_index(op.f('idx_kaveri_market'), table_name='kaveri_registrations')
    op.drop_column('kaveri_registrations', 'geom')
    op.drop_column('kaveri_registrations', 'guidance_market_gap_pct')
    op.alter_column('listings', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('listings', 'is_new_launch',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_listings_active'), table_name='listings')
    op.drop_index(op.f('idx_listings_geom'), table_name='listings', postgresql_using='gist')
    op.drop_index(op.f('idx_listings_market'), table_name='listings')
    op.drop_index(op.f('idx_listings_type'), table_name='listings')
    op.drop_constraint(op.f('listings_source_source_listing_id_key'), 'listings', type_='unique')
    op.create_unique_constraint('uq_listings_source_listing', 'listings', ['source', 'source_listing_id'])
    op.drop_column('listings', 'geom')
    op.alter_column('micro_markets', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('micro_markets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('micro_markets', 'centroid')
    op.drop_column('micro_markets', 'geom')
    op.add_column('rera_projects', sa.Column('plan_approval_date', sa.Date(), nullable=True))
    op.add_column('rera_projects', sa.Column('completion_pct', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.alter_column('rera_projects', 'blocked_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rera_projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('rera_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rera_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_rera_projects_developer'), table_name='rera_projects')
    op.drop_index(op.f('idx_rera_projects_geom'), table_name='rera_projects', postgresql_using='gist')
    op.drop_index(op.f('idx_rera_projects_market'), table_name='rera_projects')
    op.drop_index(op.f('idx_rera_projects_name_trgm'), table_name='rera_projects', postgresql_using='gin')
    op.drop_index(op.f('idx_rera_projects_number'), table_name='rera_projects')
    op.drop_index(op.f('idx_rera_projects_status'), table_name='rera_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rera_projects_status'), 'rera_projects', ['project_status'], unique=False)
    op.create_index(op.f('idx_rera_projects_number'), 'rera_projects', ['rera_number'], unique=False)
    op.create_index(op.f('idx_rera_projects_name_trgm'), 'rera_projects', ['project_name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_rera_projects_market'), 'rera_projects', ['micro_market_id'], unique=False)
    op.create_index(op.f('idx_rera_projects_geom'), 'rera_projects', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_rera_projects_developer'), 'rera_projects', ['developer_id'], unique=False)
    op.alter_column('rera_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rera_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rera_projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('rera_projects', 'blocked_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('rera_projects', 'completion_pct')
    op.drop_column('rera_projects', 'plan_approval_date')
    op.add_column('micro_markets', sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('micro_markets', sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True))
    op.alter_column('micro_markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_markets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_markets', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('listings', sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_listings_source_listing', 'listings', type_='unique')
    op.create_unique_constraint(op.f('listings_source_source_listing_id_key'), 'listings', ['source', 'source_listing_id'])
    op.create_index(op.f('idx_listings_type'), 'listings', ['transaction_type', 'property_type'], unique=False)
    op.create_index(op.f('idx_listings_market'), 'listings', ['micro_market_id'], unique=False)
    op.create_index(op.f('idx_listings_geom'), 'listings', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_listings_active'), 'listings', ['is_active', 'last_seen_at'], unique=False)
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'is_new_launch',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('listings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('listings', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('kaveri_registrations', sa.Column('guidance_market_gap_pct', sa.NUMERIC(precision=5, scale=2), sa.Computed('\nCASE\n    WHEN (guidance_value > (0)::numeric) THEN round((((transaction_amount - guidance_value) / guidance_value) * (100)::numeric), 2)\n    ELSE NULL::numeric\nEND', persisted=True), autoincrement=False, nullable=True))
    op.add_column('kaveri_registrations', sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_kaveri_market'), 'kaveri_registrations', ['micro_market_id'], unique=False)
    op.create_index(op.f('idx_kaveri_geom'), 'kaveri_registrations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_kaveri_date'), 'kaveri_registrations', ['transaction_date'], unique=False)
    op.alter_column('kaveri_registrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('guidance_values', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_developers_name_trgm'), 'developers', ['name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('developers_name_normalized_key'), 'developers', ['name_normalized'], unique=True, postgresql_where='(name_normalized IS NOT NULL)')
    op.alter_column('developers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('developers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('developers', 'total_units_sold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'total_units_launched',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'delayed_projects',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'completed_projects',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('developers', 'total_projects',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_agent_runs_status'), 'agent_runs', ['status', 'started_at'], unique=False)
    op.alter_column('agent_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_runs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_updated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_inserted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'records_scraped',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'started'::character varying"))
    op.create_index(op.f('idx_agent_memories_confidence'), 'agent_memories', [sa.literal_column('confidence DESC')], unique=False)
    op.create_index(op.f('idx_agent_memories_agent'), 'agent_memories', ['agent_id', 'market'], unique=False)
    op.alter_column('agent_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memories', 'last_confirmed',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('agent_memories', 'source_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_memories', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.6'))
    # ### end Alembic commands ###
