"""Shared Prometheus metrics for RE_OS runtime hooks.

All metric creation is idempotent — if a metric name already exists in the
global Prometheus registry, the existing metric is returned. This prevents
duplicate-registration errors during test collection when the same module
is imported via multiple paths.
"""

from prometheus_client import Counter, Histogram, REGISTRY as _R


def _counter(name: str, doc: str, labels: tuple = ()) -> Counter:
    existing = _R._names_to_collectors.get(name)
    if existing is not None:
        return existing
    try:
        return Counter(name, doc, labels)
    except ValueError:
        return _R._names_to_collectors.get(name)


def _histogram(name: str, doc: str, labels: tuple = (), buckets=None) -> Histogram:
    existing = _R._names_to_collectors.get(name)
    if existing is not None:
        return existing
    try:
        return Histogram(name, doc, labels, buckets=buckets)
    except ValueError:
        return _R._names_to_collectors.get(name)


board_session_duration_seconds = _histogram(
    "board_session_duration_seconds",
    "Wall-clock duration of board sessions (pending -> complete)",
    ["market", "status"],
    buckets=(10, 30, 60, 120, 300, 600, 1800, float("inf")),
)

pipeline_runs_total = _counter(
    "pipeline_runs_total",
    "Total number of pipeline runs",
    ["market"],
)

llm_calls_total = _counter(
    "llm_calls_total",
    "Total number of LLM kickoff calls",
    ["stage", "market"],
)

db_upserts_total = _counter(
    "db_upserts_total",
    "Total number of DB upserted/inserted records",
    ["source", "market"],
)

scrape_success_total = _counter(
    "scrape_success_total",
    "Total number of successful stage-1 scrapes",
    ["market"],
)

scraper_runs_total = _counter(
    "scraper_runs_total",
    "Scraper runs by source, market, and status",
    ["source", "market", "status"],
)

_VALID_MARKETS = frozenset({"Yelahanka", "Devanahalli", "Hebbal", "all"})


def safe_scraper_market(market: str) -> str:
    if not market or not isinstance(market, str):
        return "unknown"
    cleaned = market.strip().title()
    if cleaned in _VALID_MARKETS:
        return cleaned
    return "unknown"


llm_router_fallbacks_total = _counter(
    "llm_router_fallbacks_total",
    "LLM router fallback count by tier and provider",
    ["tier", "provider"],
)

pipeline_stage_duration_seconds = _histogram(
    "pipeline_stage_duration_seconds",
    "Pipeline stage wall-clock duration in seconds",
    ["stage"],
    buckets=(10, 30, 60, 120, 300, 600, 1200, 1800, 3600),
)

content_generation_total = _counter(
    "content_generation_total",
    "Content generation pipeline runs by market and status",
    ["market", "status"],
)

db_query_duration_seconds = _histogram(
    "db_query_duration_seconds",
    "Database query duration in seconds",
    ["query_name"],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0),
)

data_quality_checks_total = _counter(
    "data_quality_checks_total",
    "Data quality check results by market, source, and status (pass/fail/skipped/error/db_error/stale/fresh)",
    ["market", "source", "status"],
)

process_audit_reports_total = _counter(
    "process_audit_reports_total",
    "Process audit reports generated by agent and method",
    ["agent", "method"],
)

process_audit_bottlenecks_total = _counter(
    "process_audit_bottlenecks_total",
    "Bottlenecks detected by stage",
    ["stage"],
)

process_audit_runbooks_total = _counter(
    "process_audit_runbooks_total",
    "Runbook documents written by method",
    ["method"],
)

process_audit_llm_calls_total = _counter(
    "process_audit_llm_calls_total",
    "LLM calls made by process automation agents and result",
    ["agent", "result"],
)

process_audit_tasks_created_total = _counter(
    "process_audit_tasks_created_total",
    "Auto-created engineering tasks by priority",
    ["priority"],
)

optimizer_reports_generated_total = _counter(
    "optimizer_reports_generated_total",
    "Optimizer reports generated",
    ["findings_severity"],
)

optimizer_redundancy_findings_total = _counter(
    "optimizer_redundancy_findings_total",
    "Redundancy findings by type and severity",
    ["type", "severity"],
)

optimizer_tokens_tracked_total = _counter(
    "optimizer_tokens_tracked_total",
    "Total tokens tracked in optimizer reports",
    [],
)

digest_runs_total = _counter(
    "digest_runs_total",
    "Total digest runs (weekly + monthly)",
    ["digest_type", "market", "status"],
)

kaveri_deeds_records_parsed = _counter(
    "kaveri_deeds_records_parsed_total",
    "Total Kaveri deed records parsed from scout checkpoints",
    ["mode", "market"],
)

kaveri_deeds_parse_errors = _counter(
    "kaveri_deeds_parse_errors_total",
    "Total Kaveri deed parse errors",
    ["file_type"],
)

kaveri_deeds_spread_computations = _counter(
    "kaveri_deeds_spread_computations_total",
    "Total registered-vs-ask PSF spread computations",
    ["market", "status"],
)
