"""
RE_OS — Optimizer Report (Phase 9 - Sprint 60)
Generates optimization reports from token and redundancy analysis.
"""
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime, UTC
from typing import Any

import sqlalchemy

# Import metrics for optimizer instrumentation
try:
    from config.metrics import (
        optimizer_reports_generated_total,
        optimizer_redundancy_findings_total,
        optimizer_tokens_tracked_total,
    )
except Exception:
    optimizer_reports_generated_total = None
    optimizer_redundancy_findings_total = None
    optimizer_tokens_tracked_total = None

__all__ = ["OptimizerReport", "generate_report"]


@dataclass
class OptimizerReport:
    """Daily optimizer report with findings and recommendations."""

    report_date: str
    token_summary: list[dict[str, Any]] = field(default_factory=list)
    redundancy_findings: list[dict[str, Any]] = field(default_factory=list)
    cache_hit_rate: float = 0.0
    top_recommendation: str = ""
    auto_tasks_created: int = 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def write(self, path: str) -> str:
        """Write report to markdown file. Creates parent dirs if needed."""
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)

        content = f"""# RE_OS Optimizer Report — {self.report_date}

## Token Usage Summary (7-day)

| Agent | Total Tokens | Avg/Run | Budget Limit | Over Budget |
|-------|--------------|---------|--------------|-------------|
"""
        for entry in self.token_summary:
            content += (
                f"| {entry.get('agent_name', 'unknown')} | "
                f"{entry.get('total_tokens_7d', 0):,} | "
                f"{entry.get('avg_tokens_per_run', 0):.0f} | "
                f"{entry.get('budget_limit', 0):,} | "
                f"{entry.get('over_budget_runs', 0)} |\n"
            )

        content += """
## Redundancy Findings

"""
        if self.redundancy_findings:
            for finding in self.redundancy_findings:
                severity = finding.get("severity", "UNKNOWN")
                ftype = finding.get("type", "unknown")
                rec = finding.get("recommendation", "")
                content += f"- **[{severity}]** {ftype}: {rec}\n"
        else:
            content += "_No redundancies detected in the reporting period._\n"

        content += f"""
## Cache Performance

- Cache Hit Rate: {self.cache_hit_rate:.1%}

## Top Recommendation

{self.top_recommendation}

---
*Generated by RE_OS Tech Engineering Optimizer*
"""
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path


def generate_report(days: int = 1) -> OptimizerReport:
    """Generate optimizer report from token and redundancy analysis.

    Args:
        days: Number of days to look back (1-30, defaults to 1).

    Returns:
        OptimizerReport with token_summary, redundancy_findings, and top_recommendation.
    """
    if not 1 <= days <= 30:
        raise ValueError("days must be between 1 and 30")
    from utils.token_tracker import get_budget_summary
    from utils.redundancy_detector import detect_redundancies
    from intelligence.registry import IntelRegistry

    token_summary = get_budget_summary(days)
    redundancy_findings = detect_redundancies(days)

    # Get cache hit rate from IntelRegistry if available
    cache_hit_rate = 0.0
    try:
        registry = IntelRegistry()
        cache_hit_rate = _calculate_cache_hit_rate(registry)
    except Exception:
        pass

    report = OptimizerReport(
        report_date=datetime.now(UTC).strftime("%Y-%m-%d"),
        token_summary=token_summary,
        redundancy_findings=redundancy_findings,
        cache_hit_rate=cache_hit_rate,
    )

    # Emit metrics
    if optimizer_reports_generated_total:
        high_count = sum(1 for f in redundancy_findings if f.get("severity") == "HIGH")
        optimizer_reports_generated_total.labels(findings_severity="high").inc(high_count)

    if optimizer_tokens_tracked_total and token_summary:
        total = sum(e.get("total_tokens_7d", 0) for e in token_summary)
        optimizer_tokens_tracked_total.inc(total)

    if optimizer_redundancy_findings_total:
        for finding in redundancy_findings:
            optimizer_redundancy_findings_total.labels(
                type=finding.get("type", "unknown"),
                severity=finding.get("severity", "UNKNOWN"),
            ).inc()

    # Generate top recommendation
    report.top_recommendation = _generate_top_recommendation(report)

    return report


def _calculate_cache_hit_rate(registry: Any) -> float:
    """Calculate cache hit rate from registry cache stats.

    Returns 0.0 if registry has no cache or stats unavailable.
    Max capped at 0.95 to avoid overconfidence in estimates.
    """
    try:
        cache = getattr(registry, "_cache", None)
        if cache and hasattr(cache, "size") and cache.size is not None:
            total = cache.size
            if total > 0:
                return min(0.95, total / 1000.0)
    except Exception:
        pass
    return 0.0


def _generate_top_recommendation(report: OptimizerReport) -> str:
    """Generate the top recommendation string from report findings."""
    # Priority: HIGH severity redundancies first
    high_findings = [f for f in report.redundancy_findings if f.get("severity") == "HIGH"]
    for f in high_findings:
        if f.get("type") == "prompt_duplicate":
            agent = f.get("agent", "unknown")
            over = f.get("count", 0) - 1
            return f"Cache or dedup prompt for {agent} — {over} duplicate calls detected in last 2 hours. Consider memoizing identical prompts."

        if f.get("type") == "cache_miss":
            market = f.get("market", "unknown")
            return f"Review IntelRegistry cache for {market} — multiple agents hitting same market/survey in same hour suggests cache misconfiguration."

    # Then over-budget agents
    over_budget_agents = [e for e in report.token_summary if e.get("over_budget_runs", 0) > 0]
    if over_budget_agents:
        agent = over_budget_agents[0].get("agent_name", "unknown")
        over = over_budget_agents[0].get("over_budget_runs", 0)
        return f"Review token budget for {agent} — over budget {over}x in last 7 days. Consider reducing prompt length or switching to lighter model."

    return "System operating within efficiency parameters. No immediate action required."